# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk_map_article',
            fields=[
                ('hashcode', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=65000)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
            ],
        ),
    ]
